export const data = [
    {
        "id": 1,
        "name": "Product 1",
        "type": "Burger",
        "description": "Make by Berger King",
        "price": 10,
        "stars": 5,
    },
    {
        "id": 2,
        "name": "Product 2",
        "type": "Burger",
        "description": "Make by MacDonald",
        "price": 20,
        "stars": 4,
    },
    {
        "id": 3,
        "name": "Product 3",
        "type": "Pizza",
        "description": "Make by Domino's Pizza",
        "price": 30,
        "stars": 3,
    },
    {
        "id": 4,
        "name": "Product 4",
        "type": "Pizza",
        "description": "Make by Pizza Hut",
        "price": 40,
        "stars": 2,
    },
    {
        "id": 5,
        "name": "Product 5",
        "type": "Pizza",
        "description": "Make by Papa John's",
        "price": 50,
        "stars": 1,
    },
    {
        "id": 6,
        "name": "Product 6",
        "type": "Pasta",
        "description": "Make by Olive Garden",
        "price": 60,
        "stars": 5,
    },
    {
        "id": 7,
        "name": "Product 7",
        "type": "Pasta",
        "description": "Make by Carrabba's Italian Grill",
        "price": 70,
        "stars": 4,
    },
    {
        "id": 8,
        "name": "Product 8",
        "type": "Pasta",
        "description": "Make by Maggiano's Little Italy",
        "price": 80,
        "stars": 3,
    },
    {
        "id": 9,
        "name": "Product 9",
        "type": "Pasta",
        "description": "Make by Romano's Macaroni Grill",
        "price": 90,
        "stars": 2,
    },
    {
        "id": 10,
        "name": "Product 10",
        "type": "Pasta",
        "description": "Make by Fazoli's",
        "price": 100,
        "stars": 1,
    },
    {
        "id": 11,
        "name": "Product 11",
        "type": "Pasta",
        "description": "Make by Olive Garden",
        "price": 110,
        "stars": 5,
    },
    {
        "id": 12,
        "name": "Product 12",
        "type": "Pasta",
        "description": "Make by Carrabba's Italian Grill",
        "price": 120,
        "stars": 4,
    },
    {
        "id": 13,
        "name": "Product 13",
        "type": "Pizza",
        "description": "Make by Blaze Pizza",
        "price": 130,
        "stars": 3,
    },
    {
        "id": 14,
        "name": "Product 14",
        "type": "Pasta",
        "description": "Make by Romano's Macaroni Grill",
        "price": 140,
        "stars": 2,
    },
    {
        "id": 15,
        "name": "Product 15",
        "type": "Pasta",
        "description": "Make by Fazoli's",
        "price": 150,
        "stars": 1,
    },
    {
        "id": 16,
        "name": "Product 16",
        "type": "Salad",
        "description": "Make by Sweetgreen",
        "price": 160,
        "stars": 5,
    },
    {
        "id": 17,
        "name": "Product 17",
        "type": "Salad",
        "description": "Make by Just Salad",
        "price": 170,
        "stars": 4,
    },
    {
        "id": 18,
        "name": "Product 18",
        "type": "Salad",
        "description": "Make by Chopt",
        "price": 180,
        "stars": 3,
    },
    {
        "id": 19,
        "name": "Product 19",
        "type": "Salad",
        "description": "Make by Chop't",
        "price": 190,
        "stars": 2,
    },
    {
        "id": 20,
        "name": "Product 20",
        "type": "Salad",
        "description": "Make by Sweetgreen",
        "price": 200,
        "stars": 1,
    }
];


export var filteringData = data;